// Nutrición V3 — integrada al diseño aprobado
const _baseLoadSeason=loadSeason;
loadSeason=async function(id){
  const z=await _baseLoadSeason(id);
  const {data:analyses}=await db.from('analisis').select('*').eq('zafra_id',id).order('fecha',{ascending:false});
  const ids=(analyses||[]).map(a=>a.id);let results=[];
  if(ids.length){const r=await db.from('resultados_analisis').select('*').in('analisis_id',ids);results=r.data||[]}
  return {...z,analyses:analyses||[],analysisResults:results};
};
const _baseRenderSeasonTab=renderSeasonTab;
renderSeasonTab=function(tab){
  if(tab!=='nutricion')return _baseRenderSeasonTab(tab);
  const z=currentSeason;if(!z)return;
  document.querySelectorAll('.section-tabs button').forEach(b=>b.classList.toggle('active',norm(b.textContent)==='nutricion'));
  const box=document.getElementById('tabContent');
  const sum=z.ferts.reduce((a,f)=>({n:a.n+(+f.n_kg_ha||0),p:a.p+(+f.p2o5_kg_ha||0),k:a.k+(+f.k2o_kg_ha||0),s:a.s+(+f.s_kg_ha||0)}),{n:0,p:0,k:0,s:0});
  const analysisRows=(z.analyses||[]).map(a=>{const rs=(z.analysisResults||[]).filter(r=>r.analisis_id===a.id);return `<article class="timeline-item"><div class="timeline-icon">${icon('flask-conical')}</div><div><span>${fmtDate(a.fecha)}${a.estadio?' · '+esc(a.estadio):''}</span><h4>${esc(a.tipo)}</h4>${rs.length?`<p>${rs.map(r=>`${esc(r.parametro)}: <b>${r.valor??esc(r.valor_texto||'—')}</b>`).join(' · ')}</p>`:''}${a.observaciones?`<p>${esc(a.observaciones)}</p>`:''}</div><span class="row-chevron">${icon('chevron-right')}</span></article>`}).join('');
  const fertRows=(z.ferts||[]).map(f=>{const l=z.labores.find(x=>x.id===f.labor_id);return `<article class="timeline-item"><div class="timeline-icon">${icon('package-open')}</div><div><span>${fmtDate(l?.fecha)}</span><h4>${esc(f.fertilizante)} · ${Number(f.dosis_kg_ha||0).toLocaleString('es-UY')} kg/ha</h4><p>N: ${num(f.n_kg_ha)} · P₂O₅: ${num(f.p2o5_kg_ha)} · K₂O: ${num(f.k2o_kg_ha)} · S: ${num(f.s_kg_ha)} kg/ha</p></div><span class="row-chevron">${icon('chevron-right')}</span></article>`}).join('');
  box.innerHTML=`<section class="tab-panel"><div class="panel-heading"><div><h3>Nutrición</h3><p>Análisis y fertilizantes aplicados en la campaña.</p></div></div><div class="nutrient-cards"><div><span>N</span><b>${sum.n.toFixed(1)}</b><small>Nitrógeno</small></div><div><span>P</span><b>${sum.p.toFixed(1)}</b><small>Fósforo (P₂O₅)</small></div><div><span>K</span><b>${sum.k.toFixed(1)}</b><small>Potasio (K₂O)</small></div><div><span>S</span><b>${sum.s.toFixed(1)}</b><small>Azufre</small></div></div><div class="nutrition-actions"><button onclick="newAnalysis('${z.id}')">${icon('flask-conical')} Nuevo análisis</button><button onclick="newNutritionFertilizer('${z.id}')">${icon('package-plus')} Fertilizante</button></div><div class="panel-heading section-separator"><div><h3>Análisis</h3></div></div>${analysisRows?`<div class="timeline-list">${analysisRows}</div>`:`<div class="illustrated-empty compact-empty">${icon('flask-conical')}<p>Todavía no hay análisis cargados.</p></div>`}<div class="panel-heading section-separator"><div><h3>Fertilizantes aplicados</h3></div></div>${fertRows?`<div class="timeline-list">${fertRows}</div>`:`<div class="illustrated-empty compact-empty">${icon('package-open')}<p>Todavía no hay fertilizantes registrados.</p></div>`}</section>`;
  refreshIcons();
};
function num(v){return Number(v||0).toFixed(1)}
async function newAnalysis(zafra_id){
  setHeader('Nuevo análisis','NUTRICIÓN');
  content.innerHTML=`<button class="back-link" onclick="openSeason('${zafra_id}','nutricion')">${icon('arrow-left')} Volver</button><section class="form-section"><div class="section-title"><span>${icon('flask-conical')}</span><h3>Nuevo análisis</h3></div><label>Fecha</label><input id="ana_fecha" type="date" value="${new Date().toISOString().slice(0,10)}"><label>Tipo</label><select id="ana_tipo"><option>Suelo</option><option>Planta</option><option>Tejido</option><option>Otro</option></select><label>Estado fenológico</label><input id="ana_estadio" placeholder="Ej. Z22, C1, V6"><label>Resultados</label><div id="resultRows"></div><button type="button" class="secondary-cta" id="addResult">${icon('plus')} Nutriente</button><label>Observaciones</label><textarea id="ana_obs" placeholder="Observaciones (opcional)"></textarea><button id="saveAnalysis" class="primary-cta">Guardar análisis</button><div id="status"></div></section>${bottomNav('nutricion')}`;
  const rows=document.getElementById('resultRows');function addRow(){const d=document.createElement('div');d.className='analysis-row simple';d.innerHTML=`<input class="param" placeholder="Nutriente / parámetro"><input class="value" type="number" step="any" placeholder="Resultado">`;rows.appendChild(d)}addRow();document.getElementById('addResult').onclick=addRow;
  document.getElementById('saveAnalysis').onclick=async()=>{const s=document.getElementById('status');s.innerHTML=msg('Guardando…');const {data:a,error}=await db.from('analisis').insert({owner_id:user.id,zafra_id,fecha:document.getElementById('ana_fecha').value,tipo:document.getElementById('ana_tipo').value,estadio:document.getElementById('ana_estadio').value,observaciones:document.getElementById('ana_obs').value}).select().single();if(error){s.innerHTML=msg(error.message,'error');return}const rows=[...document.querySelectorAll('.analysis-row')].map(r=>({owner_id:user.id,analisis_id:a.id,parametro:r.querySelector('.param').value.trim(),valor:r.querySelector('.value').value===''?null:+r.querySelector('.value').value})).filter(r=>r.parametro);if(rows.length){const rr=await db.from('resultados_analisis').insert(rows);if(rr.error){s.innerHTML=msg(rr.error.message,'error');return}}openSeason(zafra_id,'nutricion')};refreshIcons();
}
async function newNutritionFertilizer(zafra_id){
  setHeader('Fertilizante aplicado','NUTRICIÓN');
  content.innerHTML=`<button class="back-link" onclick="openSeason('${zafra_id}','nutricion')">${icon('arrow-left')} Volver</button><section class="form-section"><div class="section-title"><span>${icon('package-plus')}</span><h3>Fertilizante aplicado</h3></div><label>Fecha</label><input id="fert_fecha" type="date" value="${new Date().toISOString().slice(0,10)}"><label>Fertilizante</label><input id="fert_nombre" placeholder="Ej. Urea azufrada"><label>Dosis de fertilizante (kg/ha)</label><input id="fert_dosis" type="number" step="any"><div class="form-grid"><div><label>N kg/ha</label><input id="fert_n" type="number" step="any"></div><div><label>P₂O₅ kg/ha</label><input id="fert_p" type="number" step="any"></div><div><label>K₂O kg/ha</label><input id="fert_k" type="number" step="any"></div><div><label>S kg/ha</label><input id="fert_s" type="number" step="any"></div></div><label>Observaciones</label><textarea id="fert_obs"></textarea><button id="saveFert" class="primary-cta">Guardar fertilización</button><div id="status"></div></section>${bottomNav('nutricion')}`;
  document.getElementById('saveFert').onclick=async()=>{const s=document.getElementById('status');s.innerHTML=msg('Guardando…');const {data:l,error}=await db.from('labores').insert({owner_id:user.id,zafra_id,fecha:document.getElementById('fert_fecha').value,tipo_labor:'fertilizacion',observaciones:document.getElementById('fert_obs').value}).select().single();if(error){s.innerHTML=msg(error.message,'error');return}const p={labor_id:l.id,owner_id:user.id,fertilizante:document.getElementById('fert_nombre').value,dosis_kg_ha:+document.getElementById('fert_dosis').value||0,n_kg_ha:+document.getElementById('fert_n').value||0,p2o5_kg_ha:+document.getElementById('fert_p').value||0,k2o_kg_ha:+document.getElementById('fert_k').value||0,s_kg_ha:+document.getElementById('fert_s').value||0};const r=await db.from('fertilizaciones').insert(p);if(r.error){await db.from('labores').delete().eq('id',l.id);s.innerHTML=msg(r.error.message,'error');return}openSeason(zafra_id,'nutricion')};refreshIcons();
}
